### ISSUE TITLE
orthographe

### ISSUE THREAD

**Issue by ninaschadel** [WildCodeSchool/2023-03-remote-fr-php-eb-conception#34]
menuiserie sans accent (page principale 2e slide)
escalier sans accent (page principale 3e slide)
Ebenisterie : sans accent car E majuscule
Mettre interligne dans tous les cadres gris (page principale) car les textes se chevauchent.

**Comment by fliewight** [comment]
+1 et le texte en uppercase -> des fois il y a les accents, et des fois non
